### ISSUE TITLE
Pre-compiled binaries throw version error

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [GinjaNinja32/cli-nbt#3]
Getting the following from the bit.ly-download-able binary, v1.1:

```
> java -jar ~/Downloads/cli-nbt-v1.1.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/gn32/apps/clinbt/Main : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by DarkStorm652** [comment]
It was compiled under Java 7 (51.0), so you need JRE/JDK 7 to run it.

**Comment by ELLIOTTCABLE** [comment]
I'm running the latest JRE:

![screenshot on 2013-08-05 at 15 58 07](https://f.cloud.github.com/assets/200/914046/ef9213ee-fe2a-11e2-835c-a58e3475c58c.png)

Is there something else I should be doing? :x

**Comment by DarkStorm652** [comment]
"Unsupported major.minor version 51.0" indicates that the JVM doesn't support class version 51.0 (which is Java 7). Make sure that the Java you're using from terminal is the same one you see in the GUI. Do java -version to verify, and if in fact it isn't the same one, you have to specify the exact path to the java binary (somewhere likely in /Library/Java/Home, but make sure it's the Java 7 one).
